syntax = "proto3";

//set namespace
package hr;

// create interface
service EmployeeService {
  rpc GetEmployee(GetEmployeeRequest) returns (EmployeeResponse);
  rpc GetEmployeesForPayroll(GetEmployeesForPayrollRequest) returns (stream EmployeeResponse);

  rpc ListDepartments(ListDepartmentsRequest) returns (stream DepartmentResponse);

  rpc CreateDepartment(CreateDepartmentRequest) returns (DepartmentResponse);
  rpc UpdateDepartment(UpdateDepartmentRequest) returns (DepartmentResponse);
  rpc DeleteDepartment(DeleteDepartmentRequest) returns (DeleteDepartmentResponse);
}

message GetEmployeesForPayrollRequest {
  int32 department_id = 1; // optional filter, 0 = semua
  string employment_status = 2; // biasanya cuma mau ACTIVE
}

// request 
message GetEmployeeRequest {
  int32 employee_id = 1;
}

//response
message EmployeeResponse {
  int32 employee_id = 1;
  string first_name = 2;
  string last_name = 3;
  string email = 4;
  double salary = 5;
  int32 job_id = 6;
  int32 department_id = 7;
  string employment_status = 8;
  string employment_type = 9;
  string hire_date = 10;
  string updated_at = 11;
}

//request
message ListDepartmentsRequest {}

//response
message DepartmentResponse {
  int32 department_id = 1;
  string department_name = 2;
}

message CreateDepartmentRequest {
  string department_name = 1;
}

message UpdateDepartmentRequest {
  int32 department_id = 1;
  optional string department_name = 2;
}

message DeleteDepartmentRequest {
  int32 department_id = 1;
}

message DeleteDepartmentResponse {
  bool success = 1;
}
